import 'dart:io';
// import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';
import '../models/match_model.dart';
import 'package:http/http.dart' as http;

class FixturePdfService {
  static Future<File> generateTournamentPdf({
    required String tournamentName,
    required List<MatchModel> matches,
    String? logoUrl,
  }) async {
    final pdf = pw.Document();

    // Load font if needed (optional, using default for now to keep it simple)
    // final font = await rootBundle.load("assets/fonts/OpenSans-Regular.ttf");
    // final ttf = pw.Font.ttf(font);

    // Group matches by Round or Date
    // For simplicity, we just list them in order, maybe grouped by date
    matches.sort((a, b) => a.scheduledTime.compareTo(b.scheduledTime));

    pw.MemoryImage? logoImage;
    if (logoUrl != null && logoUrl.isNotEmpty) {
      try {
        final response = await http.get(Uri.parse(logoUrl));
        if (response.statusCode == 200) {
          logoImage = pw.MemoryImage(response.bodyBytes);
        }
      } catch (e) {
        // Ignore image loading errors
      }
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            _buildHeader(tournamentName, logoImage),
            pw.SizedBox(height: 20),
            _buildMatchesTable(matches),
            pw.SizedBox(height: 20),
            _buildFooter(),
          ];
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File('${output.path}/tournament_schedule.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static pw.Widget _buildHeader(String title, pw.MemoryImage? logo) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              title,
              style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
            ),
            pw.Text(
              'Official Tournament Schedule',
              style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700),
            ),
            pw.Text(
              'Generated by Winniko',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
            ),
          ],
        ),
        if (logo != null)
          pw.Container(width: 60, height: 60, child: pw.Image(logo)),
      ],
    );
  }

  static pw.Widget _buildMatchesTable(List<MatchModel> matches) {
    // Define table headers
    const headers = [
      'Match',
      'Date & Time',
      'Home Team',
      'Away Team',
      'Location',
      'Round',
    ];

    final data = matches.map((match) {
      return [
        match.matchNumber?.toString() ?? '-',
        DateFormat('MMM dd, hh:mm a').format(match.scheduledTime),
        match.team1Name,
        match.team2Name,
        match.location ?? 'TBD',
        match.round ?? '-',
      ];
    }).toList();

    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: data,
      border: null,
      headerStyle: pw.TextStyle(
        fontWeight: pw.FontWeight.bold,
        color: PdfColors.white,
      ),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.green800),
      cellHeight: 30,
      cellAlignments: {
        0: pw.Alignment.center,
        1: pw.Alignment.centerLeft,
        2: pw.Alignment.centerRight,
        3: pw.Alignment.centerLeft,
        4: pw.Alignment.centerLeft,
        5: pw.Alignment.center,
      },
      oddRowDecoration: const pw.BoxDecoration(color: PdfColors.grey100),
    );
  }

  static pw.Widget _buildFooter() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Divider(color: PdfColors.grey300),
        pw.SizedBox(height: 10),
        pw.Text(
          'Track live scores and standings on the Winniko App',
          style: const pw.TextStyle(color: PdfColors.grey600, fontSize: 10),
        ),
      ],
    );
  }
}
