// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP5j3NpTNk_5CRGwT8xzWzlYqs7Ro3WdM',
    appId: '1:166236418012:web:88e941687a21c80429a919',
    messagingSenderId: '166236418012',
    projectId: 'winniko-real',
    authDomain: 'winniko-real.firebaseapp.com',
    databaseURL: 'https://winniko-real-default-rtdb.firebaseio.com',
    storageBucket: 'winniko-real.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPT0hfrAOo6x9sNNLMQJjdG_a_opYw5OU',
    appId: '1:166236418012:android:da9a8145ba1c8c1b29a919',
    messagingSenderId: '166236418012',
    projectId: 'winniko-real',
    databaseURL: 'https://winniko-real-default-rtdb.firebaseio.com',
    storageBucket: 'winniko-real.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAvIE47qPsncTRHyVVwgd2RNR3A1hw_k4',
    appId: '1:166236418012:ios:39ba60e8603c2f7029a919',
    messagingSenderId: '166236418012',
    projectId: 'winniko-real',
    databaseURL: 'https://winniko-real-default-rtdb.firebaseio.com',
    storageBucket: 'winniko-real.firebasestorage.app',
    iosBundleId: 'com.winniko.winniko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAvIE47qPsncTRHyVVwgd2RNR3A1hw_k4',
    appId: '1:166236418012:ios:39ba60e8603c2f7029a919',
    messagingSenderId: '166236418012',
    projectId: 'winniko-real',
    databaseURL: 'https://winniko-real-default-rtdb.firebaseio.com',
    storageBucket: 'winniko-real.firebasestorage.app',
    iosBundleId: 'com.winniko.winniko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP5j3NpTNk_5CRGwT8xzWzlYqs7Ro3WdM',
    appId: '1:166236418012:web:5a3ab36464e8541629a919',
    messagingSenderId: '166236418012',
    projectId: 'winniko-real',
    authDomain: 'winniko-real.firebaseapp.com',
    databaseURL: 'https://winniko-real-default-rtdb.firebaseio.com',
    storageBucket: 'winniko-real.firebasestorage.app',
  );
}
