// ignore_for_file: use_build_context_synchronously

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import 'package:image_picker/image_picker.dart';
import 'package:cached_network_image/cached_network_image.dart';
import '../constants/app_constants.dart';
import '../widgets/loading_spinner.dart';
import '../models/competition_model.dart';
import '../models/message_model.dart';
import '../services/firestore_service.dart';
import '../services/auth_service.dart';
import '../services/storage_service.dart';

class CompetitionChatScreen extends StatefulWidget {
  final CompetitionModel competition;
  final bool isParticipant;

  const CompetitionChatScreen({
    super.key,
    required this.competition,
    required this.isParticipant,
  });

  @override
  State<CompetitionChatScreen> createState() => _CompetitionChatScreenState();
}

class _CompetitionChatScreenState extends State<CompetitionChatScreen> {
  final TextEditingController _messageController = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  bool _isSending = false;
  bool _isTyping = false;
  DateTime? _lastTypingTime;

  @override
  void initState() {
    super.initState();
    _markAsRead();
  }

  @override
  void dispose() {
    _markAsRead();
    _messageController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  void _markAsRead() {
    // Fire and forget - mark as read when entering/leaving chat
    final authService = Provider.of<AuthService>(context, listen: false);
    final userId = authService.currentUserId;
    if (userId != null) {
      Provider.of<FirestoreService>(
        context,
        listen: false,
      ).markCompetitionChatRead(widget.competition.id, userId);
    }
  }

  Future<void> _sendMessage() async {
    final text = _messageController.text.trim();
    if (text.isEmpty) return;

    if (!context.mounted) return;
    final authService = Provider.of<AuthService>(context, listen: false);
    final firestoreService = Provider.of<FirestoreService>(
      context,
      listen: false,
    );
    final user = await authService.getUserProfile(authService.currentUserId!);

    if (user == null) return;

    setState(() {
      _isSending = true;
    });

    try {
      final isOrganizer = widget.competition.organizerId == user.id;

      final message = MessageModel(
        id: '', // Generated by Firestore
        senderId: user.id,
        senderName: user.name,
        text: text,
        timestamp: DateTime.now(),
        isOrganizer: isOrganizer,
      );

      await firestoreService.sendMessage(widget.competition.id, message);
      _messageController.clear();

      // Scroll to bottom
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          0,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Failed to send message: $e')));
    } finally {
      if (mounted) setState(() => _isSending = false);
    }
  }

  Future<void> _updateTypingStatus(bool isTyping) async {
    if (_isTyping == isTyping) return;
    _isTyping = isTyping;

    final authService = Provider.of<AuthService>(context, listen: false);
    final firestoreService = Provider.of<FirestoreService>(
      context,
      listen: false,
    );
    final userId = authService.currentUserId;
    if (userId != null) {
      final user = await authService.getUserProfile(userId);
      if (!mounted) return;
      if (user != null) {
        await firestoreService.setTypingStatus(
          widget.competition.id,
          user.id,
          user.name,
          isTyping,
        );
      }
    }
  }

  void _onTextChanged(String text) {
    if (text.isNotEmpty) {
      _updateTypingStatus(true);
      _lastTypingTime = DateTime.now();
      Future.delayed(const Duration(seconds: 5), () {
        if (_lastTypingTime != null &&
            DateTime.now().difference(_lastTypingTime!) >=
                const Duration(seconds: 5)) {
          _updateTypingStatus(false);
        }
      });
    } else {
      _updateTypingStatus(false);
    }
  }

  Future<void> _pickImage() async {
    if (_isSending) return;

    final ImagePicker picker = ImagePicker();
    final XFile? image = await picker.pickImage(
      source: ImageSource.gallery,
      imageQuality: 70,
    );

    if (image == null) return;

    setState(() => _isSending = true);

    try {
      final storageService = StorageService();
      final imageUrl = await storageService.uploadChatMessage(
        // Using existing method, path will be competitions/ID/chats/global/fileName for global chat
        file: image,
        competitionId: widget.competition.id,
        participantId: 'global',
      );

      if (!context.mounted) return;
      final authService = Provider.of<AuthService>(context, listen: false);
      final firestoreService = Provider.of<FirestoreService>(
        context,
        listen: false,
      );
      final user = await authService.getUserProfile(authService.currentUserId!);

      if (user != null) {
        final isOrganizer = widget.competition.organizerId == user.id;
        final message = MessageModel(
          id: '',
          senderId: user.id,
          senderName: user.name,
          text: '',
          timestamp: DateTime.now(),
          isOrganizer: isOrganizer,
          imageUrl: imageUrl,
        );

        await firestoreService.sendMessage(widget.competition.id, message);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Failed to upload: $e')));
      }
    } finally {
      if (mounted) setState(() => _isSending = false);
    }
  }

  Future<void> _togglePin(MessageModel message) async {
    final authService = Provider.of<AuthService>(context, listen: false);
    if (widget.competition.organizerId != authService.currentUserId) return;

    final firestoreService = Provider.of<FirestoreService>(
      context,
      listen: false,
    );
    try {
      await firestoreService.pinCompetitionMessage(
        competitionId: widget.competition.id,
        messageId: message.id,
        isPinned: !message.isPinned,
      );
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  Future<void> _deleteMessage(String messageId) async {
    final firestoreService = Provider.of<FirestoreService>(
      context,
      listen: false,
    );
    try {
      await firestoreService.deleteCompetitionMessage(
        widget.competition.id,
        messageId,
      );
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<AuthService>(context, listen: false);
    final currentUserId = authService.currentUserId;
    final firestoreService = Provider.of<FirestoreService>(
      context,
      listen: false,
    );

    return Scaffold(
      backgroundColor: AppColors.backgroundDark,
      body: Column(
        children: [
          Expanded(
            child: StreamBuilder<List<MessageModel>>(
              stream: firestoreService.getMessages(widget.competition.id),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(
                    child: LoadingSpinner(color: AppColors.accentGreen),
                  );
                }

                if (snapshot.hasError) {
                  return Center(
                    child: Text(
                      'Error: ${snapshot.error}',
                      style: const TextStyle(color: AppColors.error),
                    ),
                  );
                }

                final messages = snapshot.data ?? [];
                final pinnedMessages = messages
                    .where((m) => m.isPinned)
                    .toList();

                if (messages.isEmpty) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const Icon(
                          Icons.chat_bubble_outline,
                          size: 64,
                          color: AppColors.textSecondary,
                        ),
                        const SizedBox(height: 16),
                        const Text(
                          'No messages yet',
                          style: TextStyle(color: AppColors.textSecondary),
                        ),
                        const SizedBox(height: 8),
                        if (widget.isParticipant ||
                            widget.competition.organizerId == currentUserId)
                          const Text(
                            'Start the conversation!',
                            style: TextStyle(
                              color: AppColors.textSecondary,
                              fontSize: 12,
                            ),
                          ),
                      ],
                    ),
                  );
                }

                return Column(
                  children: [
                    if (pinnedMessages.isNotEmpty)
                      _buildPinnedBanner(pinnedMessages.first, currentUserId),
                    Expanded(
                      child: ListView.builder(
                        reverse: true, // Show newest at bottom
                        controller: _scrollController,
                        padding: const EdgeInsets.all(16),
                        itemCount: messages.length,
                        itemBuilder: (context, index) {
                          final message = messages[index];
                          final isMe = message.senderId == currentUserId;

                          // Mark as read if it's not from me
                          if (!isMe &&
                              !message.readBy.contains(currentUserId)) {
                            firestoreService.markMessageAsRead(
                              widget.competition.id,
                              message.id,
                              currentUserId!,
                            );
                          }

                          return _buildMessageBubble(
                            message,
                            isMe,
                            currentUserId == widget.competition.organizerId,
                          );
                        },
                      ),
                    ),
                    _buildTypingIndicator(currentUserId),
                  ],
                );
              },
            ),
          ),

          if (widget.isParticipant ||
              widget.competition.organizerId == currentUserId)
            _buildInputArea(),
        ],
      ),
    );
  }

  Widget _buildPinnedBanner(MessageModel message, String? currentUserId) {
    final isOrganizer = currentUserId == widget.competition.organizerId;
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      color: AppColors.accentGreen.withValues(alpha: 0.1),
      child: Row(
        children: [
          const Icon(Icons.push_pin, size: 16, color: AppColors.accentGreen),
          const SizedBox(width: 8),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'Pinned Message',
                  style: TextStyle(
                    color: AppColors.accentGreen,
                    fontSize: 10,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                Text(
                  message.text.isNotEmpty ? message.text : '📷 Image',
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: const TextStyle(color: Colors.white, fontSize: 12),
                ),
              ],
            ),
          ),
          if (isOrganizer)
            IconButton(
              icon: const Icon(
                Icons.close,
                size: 16,
                color: AppColors.textSecondary,
              ),
              onPressed: () => _togglePin(message),
            ),
        ],
      ),
    );
  }

  Widget _buildMessageBubble(
    MessageModel message,
    bool isMe,
    bool amIOrganizer,
  ) {
    if (message.isSystem) {
      return Padding(
        padding: const EdgeInsets.symmetric(vertical: 8.0),
        child: Center(
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
            decoration: BoxDecoration(
              color: AppColors.cardBackground,
              borderRadius: BorderRadius.circular(12),
            ),
            child: Text(
              message.text,
              style: const TextStyle(
                color: AppColors.textSecondary,
                fontSize: 12,
              ),
            ),
          ),
        ),
      );
    }

    return GestureDetector(
      onLongPress: (amIOrganizer || isMe)
          ? () {
              showModalBottomSheet(
                context: context,
                backgroundColor: AppColors.cardBackground,
                builder: (context) => Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    if (amIOrganizer)
                      ListTile(
                        leading: Icon(
                          message.isPinned
                              ? Icons.push_pin_outlined
                              : Icons.push_pin,
                          color: Colors.white,
                        ),
                        title: Text(
                          message.isPinned ? 'Unpin Message' : 'Pin Message',
                          style: const TextStyle(color: Colors.white),
                        ),
                        onTap: () {
                          Navigator.pop(context);
                          _togglePin(message);
                        },
                      ),
                    ListTile(
                      leading: const Icon(Icons.delete, color: AppColors.error),
                      title: const Text(
                        'Delete Message',
                        style: TextStyle(color: AppColors.error),
                      ),
                      onTap: () {
                        Navigator.pop(context);
                        _deleteMessage(message.id);
                      },
                    ),
                  ],
                ),
              );
            }
          : null,
      child: Padding(
        padding: const EdgeInsets.only(bottom: 12.0),
        child: Column(
          crossAxisAlignment: isMe
              ? CrossAxisAlignment.end
              : CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.end,
              mainAxisAlignment: isMe
                  ? MainAxisAlignment.end
                  : MainAxisAlignment.start,
              children: [
                if (!isMe && !message.isOrganizer) ...[
                  CircleAvatar(
                    radius: 16,
                    backgroundColor: AppColors.textSecondary,
                    child: Text(
                      message.senderName[0].toUpperCase(),
                      style: const TextStyle(color: Colors.white, fontSize: 12),
                    ),
                  ),
                  const SizedBox(width: 8),
                ],
                if (!isMe && message.isOrganizer) ...[
                  const CircleAvatar(
                    radius: 16,
                    backgroundColor: AppColors.accentGreen,
                    child: Icon(Icons.star, color: Colors.white, size: 16),
                  ),
                  const SizedBox(width: 8),
                ],
                Flexible(
                  child: Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 16,
                      vertical: 10,
                    ),
                    decoration: BoxDecoration(
                      color: isMe
                          ? AppColors.primaryGreen
                          : (message.isOrganizer
                                ? AppColors.accentGreen.withValues(alpha: 0.2)
                                : AppColors.cardBackground),
                      borderRadius: BorderRadius.only(
                        topLeft: const Radius.circular(16),
                        topRight: const Radius.circular(16),
                        bottomLeft: isMe
                            ? const Radius.circular(16)
                            : Radius.zero,
                        bottomRight: isMe
                            ? Radius.zero
                            : const Radius.circular(16),
                      ),
                      border: (message.isOrganizer && !isMe) || message.isPinned
                          ? Border.all(
                              color: message.isPinned
                                  ? AppColors.accentGreen
                                  : AppColors.accentGreen.withValues(
                                      alpha: 0.5,
                                    ),
                              width: message.isPinned ? 2 : 1,
                            )
                          : null,
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        if (!isMe)
                          Text(
                            message.isOrganizer
                                ? 'Organizer • ${message.senderName}'
                                : message.senderName,
                            style: TextStyle(
                              color: message.isOrganizer
                                  ? AppColors.accentGreen
                                  : AppColors.textSecondary,
                              fontSize: 10,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        if (!isMe) const SizedBox(height: 4),
                        if (message.imageUrl != null)
                          Padding(
                            padding: const EdgeInsets.symmetric(vertical: 4.0),
                            child: ClipRRect(
                              borderRadius: BorderRadius.circular(8),
                              child: CachedNetworkImage(
                                imageUrl: message.imageUrl!,
                                placeholder: (context, url) => const SizedBox(
                                  width: 200,
                                  height: 200,
                                  child: Center(
                                    child: LoadingSpinner(size: 20),
                                  ),
                                ),
                                errorWidget: (context, url, error) =>
                                    const Icon(
                                      Icons.error,
                                      color: AppColors.error,
                                    ),
                                fit: BoxFit.cover,
                              ),
                            ),
                          ),
                        if (message.text.isNotEmpty)
                          Text(
                            message.text,
                            style: const TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                            ),
                          ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
            Padding(
              padding: const EdgeInsets.only(top: 4, left: 40, right: 0),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  if (message.isPinned)
                    const Padding(
                      padding: EdgeInsets.only(right: 8),
                      child: Icon(
                        Icons.push_pin,
                        size: 10,
                        color: AppColors.accentGreen,
                      ),
                    ),
                  Text(
                    DateFormat('h:mm a').format(message.timestamp),
                    style: TextStyle(color: Colors.grey[600], fontSize: 10),
                  ),
                  if (isMe) ...[
                    const SizedBox(width: 4),
                    Icon(
                      message.readBy.isNotEmpty ? Icons.done_all : Icons.done,
                      size: 14,
                      color: message.readBy.isNotEmpty
                          ? AppColors.accentGreen
                          : Colors.grey[600],
                    ),
                  ],
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTypingIndicator(String? currentUserId) {
    if (currentUserId == null) return const SizedBox.shrink();
    final firestoreService = Provider.of<FirestoreService>(
      context,
      listen: false,
    );
    return StreamBuilder<List<String>>(
      stream: firestoreService.getTypingUsers(
        widget.competition.id,
        currentUserId,
      ),
      builder: (context, snapshot) {
        if (!snapshot.hasData || snapshot.data!.isEmpty) {
          return const SizedBox.shrink();
        }
        final users = snapshot.data!;
        String text = users.length == 1
            ? '${users[0]} is typing...'
            : '${users.length} people are typing...';
        return Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 4.0),
          child: Row(
            children: [
              const SizedBox(
                width: 12,
                height: 12,
                child: CircularProgressIndicator(
                  strokeWidth: 2,
                  valueColor: AlwaysStoppedAnimation<Color>(
                    AppColors.accentGreen,
                  ),
                ),
              ),
              const SizedBox(width: 8),
              Text(
                text,
                style: const TextStyle(
                  color: AppColors.textSecondary,
                  fontSize: 10,
                  fontStyle: FontStyle.italic,
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  Widget _buildInputArea() {
    final authService = Provider.of<AuthService>(context, listen: false);
    final isOrganizer =
        widget.competition.organizerId == authService.currentUserId;

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppColors.cardBackground,
        border: Border(top: BorderSide(color: AppColors.dividerColor)),
      ),
      child: Row(
        children: [
          if (isOrganizer) ...[
            IconButton(
              icon: const Icon(Icons.image, color: AppColors.accentGreen),
              onPressed: _isSending ? null : _pickImage,
            ),
            const SizedBox(width: 8),
          ],
          Expanded(
            child: TextField(
              controller: _messageController,
              style: const TextStyle(color: Colors.white),
              textCapitalization: TextCapitalization.sentences,
              decoration: InputDecoration(
                hintText: 'Type a message...',
                hintStyle: const TextStyle(color: AppColors.textSecondary),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(24),
                  borderSide: BorderSide.none,
                ),
                filled: true,
                fillColor: AppColors.backgroundDark,
                contentPadding: const EdgeInsets.symmetric(
                  horizontal: 20,
                  vertical: 10,
                ),
              ),
              onChanged: _onTextChanged,
              onSubmitted: (_) {
                _sendMessage();
                _updateTypingStatus(false);
              },
            ),
          ),
          const SizedBox(width: 8),
          Container(
            decoration: const BoxDecoration(
              color: AppColors.accentGreen,
              shape: BoxShape.circle,
            ),
            child: IconButton(
              icon: _isSending
                  ? const SizedBox(
                      width: 20,
                      height: 20,
                      child: LoadingSpinner(size: 20, color: Colors.white),
                    )
                  : const Icon(Icons.send, color: Colors.white),
              onPressed: _isSending ? null : _sendMessage,
            ),
          ),
        ],
      ),
    );
  }
}
