// ignore_for_file: use_build_context_synchronously

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import 'package:image_picker/image_picker.dart';
import 'package:cached_network_image/cached_network_image.dart';
import '../constants/app_constants.dart';
import '../models/message_model.dart';
import '../services/firestore_service.dart';
import '../services/auth_service.dart';
import '../services/storage_service.dart';
import '../widgets/loading_spinner.dart';

class DirectChatScreen extends StatefulWidget {
  final String competitionId;
  final String
  participantId; // The ID of the participant involved (could be me or the person I'm chatting with)
  final String participantName; // Updates on send
  final bool
  amIOrganizer; // If I am organizer, I am chatting with participantId. If I am participant, participantId is ME.

  // Helper getters
  String get chatDocId =>
      participantId; // The chat doc is always keyed by participantId

  const DirectChatScreen({
    super.key,
    required this.competitionId,
    required this.participantId,
    required this.participantName,
    required this.amIOrganizer,
  });

  @override
  State<DirectChatScreen> createState() => _DirectChatScreenState();
}

class _DirectChatScreenState extends State<DirectChatScreen> {
  final TextEditingController _messageController = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  bool _isSending = false;
  bool _isTyping = false;
  DateTime? _lastTypingTime;

  @override
  void initState() {
    super.initState();
    // Mark as read on enter
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _markAsRead();
    });
  }

  void _markAsRead() {
    final firestoreService = Provider.of<FirestoreService>(
      context,
      listen: false,
    );
    firestoreService.markChatRead(
      competitionId: widget.competitionId,
      participantId: widget.participantId,
      isOrganizerReading: widget.amIOrganizer,
    );
  }

  @override
  void dispose() {
    _messageController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  Future<void> _sendMessage() async {
    final text = _messageController.text.trim();
    if (text.isEmpty) return;

    final authService = Provider.of<AuthService>(context, listen: false);
    final firestoreService = Provider.of<FirestoreService>(
      context,
      listen: false,
    );
    final user = await authService.getUserProfile(authService.currentUserId!);

    if (user == null) return;

    setState(() => _isSending = true);

    try {
      final message = MessageModel(
        id: '', // Generated by Firestore
        senderId: user.id,
        senderName: user.name,
        text: text,
        timestamp: DateTime.now(),
        isOrganizer: widget.amIOrganizer,
      );

      await firestoreService.sendDirectMessage(
        competitionId: widget.competitionId,
        participantId: widget.participantId,
        message: message,
        participantName: widget.amIOrganizer
            ? widget.participantName
            : user.name, // If I am participant, update my name
      );

      _messageController.clear();

      // Scroll to bottom
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          0,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Failed to send: $e')));
      }
    } finally {
      if (mounted) setState(() => _isSending = false);
    }
  }

  Future<void> _updateTypingStatus(bool isTyping) async {
    if (_isTyping == isTyping) return;
    _isTyping = isTyping;

    final authService = Provider.of<AuthService>(context, listen: false);
    final firestoreService = Provider.of<FirestoreService>(
      context,
      listen: false,
    );
    final userId = authService.currentUserId;
    if (userId != null) {
      final user = await authService.getUserProfile(userId);
      if (user != null) {
        await firestoreService.setDirectTypingStatus(
          widget.competitionId,
          widget.participantId,
          user.id,
          user.name,
          isTyping,
        );
      }
    }
  }

  void _onTextChanged(String text) {
    if (text.isNotEmpty) {
      _updateTypingStatus(true);
      _lastTypingTime = DateTime.now();
      Future.delayed(const Duration(seconds: 5), () {
        if (_lastTypingTime != null &&
            DateTime.now().difference(_lastTypingTime!) >=
                const Duration(seconds: 5)) {
          _updateTypingStatus(false);
        }
      });
    } else {
      _updateTypingStatus(false);
    }
  }

  Future<void> _pickImage() async {
    if (_isSending) return;

    final ImagePicker picker = ImagePicker();
    final XFile? image = await picker.pickImage(
      source: ImageSource.gallery,
      imageQuality: 70,
    );

    if (image == null) return;

    setState(() => _isSending = true);

    try {
      final storageService = StorageService();
      final imageUrl = await storageService.uploadChatMessage(
        file: image,
        competitionId: widget.competitionId,
        participantId: widget.participantId,
      );

      if (!context.mounted) return;
      final authService = Provider.of<AuthService>(context, listen: false);
      final firestoreService = Provider.of<FirestoreService>(
        context,
        listen: false,
      );
      final user = await authService.getUserProfile(authService.currentUserId!);

      if (user != null) {
        final message = MessageModel(
          id: '',
          senderId: user.id,
          senderName: user.name,
          text: '', // Empty text for image-only messages
          timestamp: DateTime.now(),
          isOrganizer: widget.amIOrganizer,
          imageUrl: imageUrl,
        );

        await firestoreService.sendDirectMessage(
          competitionId: widget.competitionId,
          participantId: widget.participantId,
          message: message,
          participantName: widget.participantName,
        );
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Failed to upload: $e')));
    } finally {
      if (mounted) setState(() => _isSending = false);
    }
  }

  Future<void> _deleteConversation() async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Conversation'),
        content: const Text(
          'Are you sure you want to delete this conversation? This will remove all messages for you and the other party.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            style: TextButton.styleFrom(foregroundColor: AppColors.error),
            child: const Text('Delete'),
          ),
        ],
      ),
    );

    if (confirmed == true) {
      if (!context.mounted) return;
      final firestoreService = Provider.of<FirestoreService>(
        context,
        listen: false,
      );
      try {
        await firestoreService.deleteDirectChat(
          competitionId: widget.competitionId,
          participantId: widget.participantId,
        );
        if (mounted) {
          Navigator.pop(context);
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(const SnackBar(content: Text('Conversation deleted')));
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Error: $e')));
        }
      }
    }
  }

  Future<void> _deleteMessage(String messageId) async {
    final firestore = Provider.of<FirestoreService>(context, listen: false);
    try {
      await firestore.deleteDirectMessage(
        competitionId: widget.competitionId,
        participantId: widget.participantId,
        messageId: messageId,
      );
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error deleting message: $e')));
      }
    }
  }

  Future<void> _togglePin(MessageModel message) async {
    if (!widget.amIOrganizer) return;

    final firestoreService = Provider.of<FirestoreService>(
      context,
      listen: false,
    );
    try {
      await firestoreService.pinDirectMessage(
        competitionId: widget.competitionId,
        participantId: widget.participantId,
        messageId: message.id,
        isPinned: !message.isPinned,
      );
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final firestoreService = Provider.of<FirestoreService>(
      context,
      listen: false,
    );
    final authService = Provider.of<AuthService>(context, listen: false);
    final currentUserId = authService.currentUserId;

    return Scaffold(
      backgroundColor: AppColors.backgroundDark,
      appBar: AppBar(
        title: Text(widget.amIOrganizer ? widget.participantName : 'Organizer'),
        backgroundColor: AppColors.primaryGreen,
        actions: [
          PopupMenuButton<String>(
            onSelected: (value) {
              if (value == 'delete') _deleteConversation();
            },
            itemBuilder: (context) => [
              const PopupMenuItem(
                value: 'delete',
                child: Row(
                  children: [
                    Icon(Icons.delete, color: AppColors.error, size: 20),
                    SizedBox(width: 8),
                    Text(
                      'Delete Conversation',
                      style: TextStyle(color: AppColors.error),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: StreamBuilder<List<MessageModel>>(
              stream: firestoreService.getDirectMessages(
                widget.competitionId,
                widget.participantId,
              ),
              builder: (context, snapshot) {
                if (snapshot.hasError) {
                  return Center(child: Text('Error: ${snapshot.error}'));
                }
                if (!snapshot.hasData) {
                  return const Center(child: LoadingSpinner());
                }

                final messages = snapshot.data!;
                final pinnedMessages = messages
                    .where((m) => m.isPinned)
                    .toList();

                if (messages.isEmpty) {
                  return const Center(
                    child: Text(
                      'No messages yet',
                      style: TextStyle(color: AppColors.textSecondary),
                    ),
                  );
                }

                return Column(
                  children: [
                    if (pinnedMessages.isNotEmpty)
                      _buildPinnedBanner(pinnedMessages.first),
                    Expanded(
                      child: ListView.builder(
                        reverse: true,
                        controller: _scrollController,
                        padding: const EdgeInsets.all(16),
                        itemCount: messages.length,
                        itemBuilder: (context, index) {
                          final message = messages[index];
                          final isMe = message.senderId == currentUserId;

                          // Mark as read if not from me
                          if (!isMe &&
                              !message.readBy.contains(currentUserId)) {
                            firestoreService.markDirectMessageAsRead(
                              widget.competitionId,
                              widget.participantId,
                              message.id,
                              currentUserId!,
                            );
                          }

                          return _buildMessageBubble(message, isMe);
                        },
                      ),
                    ),
                    _buildTypingIndicator(currentUserId),
                  ],
                );
              },
            ),
          ),
          _buildInputArea(),
        ],
      ),
    );
  }

  Widget _buildPinnedBanner(MessageModel message) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      color: AppColors.accentGreen.withValues(alpha: 0.1),
      child: Row(
        children: [
          const Icon(Icons.push_pin, size: 16, color: AppColors.accentGreen),
          const SizedBox(width: 8),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'Pinned Message',
                  style: TextStyle(
                    color: AppColors.accentGreen,
                    fontSize: 10,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                Text(
                  message.text,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: const TextStyle(color: Colors.white, fontSize: 12),
                ),
              ],
            ),
          ),
          if (widget.amIOrganizer)
            IconButton(
              icon: const Icon(
                Icons.close,
                size: 16,
                color: AppColors.textSecondary,
              ),
              onPressed: () => _togglePin(message),
            ),
        ],
      ),
    );
  }

  Widget _buildMessageBubble(MessageModel message, bool isMe) {
    return GestureDetector(
      onLongPress: (widget.amIOrganizer || isMe)
          ? () {
              showModalBottomSheet(
                context: context,
                backgroundColor: AppColors.cardBackground,
                builder: (context) => Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    if (widget.amIOrganizer)
                      ListTile(
                        leading: Icon(
                          message.isPinned
                              ? Icons.push_pin_outlined
                              : Icons.push_pin,
                          color: Colors.white,
                        ),
                        title: Text(
                          message.isPinned ? 'Unpin Message' : 'Pin Message',
                          style: const TextStyle(color: Colors.white),
                        ),
                        onTap: () {
                          Navigator.pop(context);
                          _togglePin(message);
                        },
                      ),
                    ListTile(
                      leading: const Icon(Icons.delete, color: AppColors.error),
                      title: const Text(
                        'Delete Message',
                        style: TextStyle(color: AppColors.error),
                      ),
                      onTap: () {
                        Navigator.pop(context);
                        _deleteMessage(message.id);
                      },
                    ),
                  ],
                ),
              );
            }
          : null,
      child: Padding(
        padding: const EdgeInsets.only(bottom: 12.0),
        child: Column(
          crossAxisAlignment: isMe
              ? CrossAxisAlignment.end
              : CrossAxisAlignment.start,
          children: [
            if (message.isPinned)
              const Padding(
                padding: EdgeInsets.only(bottom: 4),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(
                      Icons.push_pin,
                      size: 12,
                      color: AppColors.accentGreen,
                    ),
                    SizedBox(width: 4),
                    Text(
                      'Pinned',
                      style: TextStyle(
                        color: AppColors.accentGreen,
                        fontSize: 10,
                      ),
                    ),
                  ],
                ),
              ),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
              decoration: BoxDecoration(
                color: isMe
                    ? AppColors.primaryGreen
                    : (message.isOrganizer
                          ? AppColors.accentGreen.withValues(alpha: 0.2)
                          : AppColors.cardBackground),
                borderRadius: BorderRadius.only(
                  topLeft: const Radius.circular(16),
                  topRight: const Radius.circular(16),
                  bottomLeft: isMe ? const Radius.circular(16) : Radius.zero,
                  bottomRight: isMe ? Radius.zero : const Radius.circular(16),
                ),
                border: (message.isOrganizer && !isMe) || message.isPinned
                    ? Border.all(
                        color: message.isPinned
                            ? AppColors.accentGreen
                            : AppColors.accentGreen.withValues(alpha: 0.5),
                        width: message.isPinned ? 2 : 1,
                      )
                    : null,
              ),
              child: message.imageUrl != null
                  ? Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        ClipRRect(
                          borderRadius: BorderRadius.circular(8),
                          child: CachedNetworkImage(
                            imageUrl: message.imageUrl!,
                            placeholder: (context, url) => const SizedBox(
                              width: 200,
                              height: 200,
                              child: Center(child: LoadingSpinner(size: 20)),
                            ),
                            errorWidget: (context, url, error) =>
                                const Icon(Icons.error, color: AppColors.error),
                            fit: BoxFit.cover,
                          ),
                        ),
                        if (message.text.isNotEmpty) ...[
                          const SizedBox(height: 8),
                          Text(
                            message.text,
                            style: const TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                            ),
                          ),
                        ],
                      ],
                    )
                  : Text(
                      message.text,
                      style: const TextStyle(color: Colors.white, fontSize: 15),
                    ),
            ),
            Padding(
              padding: const EdgeInsets.only(top: 4, left: 4),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(
                    DateFormat('h:mm a').format(message.timestamp),
                    style: TextStyle(color: Colors.grey[600], fontSize: 10),
                  ),
                  if (isMe) ...[
                    const SizedBox(width: 4),
                    Icon(
                      message.readBy.isNotEmpty ? Icons.done_all : Icons.done,
                      size: 14,
                      color: message.readBy.isNotEmpty
                          ? AppColors.accentGreen
                          : Colors.grey[600],
                    ),
                  ],
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTypingIndicator(String? currentUserId) {
    if (currentUserId == null) return const SizedBox.shrink();
    final firestoreService = Provider.of<FirestoreService>(
      context,
      listen: false,
    );
    return StreamBuilder<List<String>>(
      stream: firestoreService.getDirectTypingUsers(
        widget.competitionId,
        widget.participantId,
        currentUserId,
      ),
      builder: (context, snapshot) {
        if (!snapshot.hasData || snapshot.data!.isEmpty) {
          return const SizedBox.shrink();
        }
        final users = snapshot.data!;
        String text = '${users[0]} is typing...';
        return Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 4.0),
          child: Row(
            children: [
              const SizedBox(
                width: 12,
                height: 12,
                child: CircularProgressIndicator(
                  strokeWidth: 2,
                  valueColor: AlwaysStoppedAnimation<Color>(
                    AppColors.accentGreen,
                  ),
                ),
              ),
              const SizedBox(width: 8),
              Text(
                text,
                style: const TextStyle(
                  color: AppColors.textSecondary,
                  fontSize: 10,
                  fontStyle: FontStyle.italic,
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  Widget _buildInputArea() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: const BoxDecoration(
        color: AppColors.cardBackground,
        border: Border(top: BorderSide(color: AppColors.dividerColor)),
      ),
      child: Row(
        children: [
          IconButton(
            icon: const Icon(Icons.image, color: AppColors.accentGreen),
            onPressed: _isSending ? null : _pickImage,
          ),
          const SizedBox(width: 8),
          Expanded(
            child: TextField(
              controller: _messageController,
              style: const TextStyle(color: Colors.white),
              textCapitalization: TextCapitalization.sentences,
              decoration: InputDecoration(
                hintText: 'Type a message...',
                hintStyle: const TextStyle(color: AppColors.textSecondary),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(24),
                  borderSide: BorderSide.none,
                ),
                filled: true,
                fillColor: AppColors.backgroundDark,
                contentPadding: const EdgeInsets.symmetric(
                  horizontal: 20,
                  vertical: 10,
                ),
              ),
              onChanged: _onTextChanged,
              onSubmitted: (_) {
                _sendMessage();
                _updateTypingStatus(false);
              },
            ),
          ),
          const SizedBox(width: 8),
          Container(
            decoration: const BoxDecoration(
              color: AppColors.accentGreen,
              shape: BoxShape.circle,
            ),
            child: IconButton(
              icon: _isSending
                  ? const SizedBox(
                      width: 20,
                      height: 20,
                      child: LoadingSpinner(color: Colors.white, size: 20),
                    )
                  : const Icon(Icons.send, color: Colors.white),
              onPressed: _isSending ? null : _sendMessage,
            ),
          ),
        ],
      ),
    );
  }
}
